### ISSUE TITLE
phnemes_ud result explanation

### ISSUE THREAD

**Issue by Chunyan-Hou** [saezlab/PHONEMeS#13]
Hello, I am using PHONEMeS-ILP and curious about the meaning of the column nodesP in nodesAttributes.txt. What do D and P in this column represent? 

Many thanks,
Chunyan

**Comment by smuellerd** [comment]
Hi @Chunyan-Hou,

the column nodesP highlights the selected kinases and phosphorylation sites before running the upside-down variant of PHONEMeS. "D" stands for the deregulated kinases that have been selected based on the kinase enrichment analysis and "P" stands for the deregulated phosphorylation sites selected based on the thresholds set in the buildInputs function. 

On another note, you could also try running our main function implemented in this Phonemes repo. It also uses the ILP formulation and CPLEX now plus takes the direction of deregulation into account and additionally includes protein-protein interactions in the prior knowledge. It also comes with a tutorial on how to run it: https://github.com/saezlab/PHONEMeS/blob/master/vignettes/tutorial.md. 

Best
Sophia
