### ISSUE TITLE
Running Phonemes on a multi core AWS instance?

### ISSUE THREAD

**Issue by saksham219** [saezlab/PHONEMeS#2]
Hi
I am planning to run Phonemes for some phosphoproteomic datasets. However I do not have IBM clusters available. Is it possible to run it on a multi core AWS system(16 cores, 60GB) ? If yes, can you point out where I would want to make changes. Thanks in advance.

**Comment by enio23** [comment]
Hello,

Thank you for your interest on using PHONEMeS. If you would like to run the tool in a cluster, then the modifications might have to be done in the shell script which is submitting and executing the jobs. On that case I would need to know the specifications of the cluster you will be using.

However, an alternative approach would be on using a new ILP implementation which makes the running much simpler in a stand alone PC and much faster. For that however, I would suggest you to first obtain a CPLEX license from IBM (https://www.ibm.com/products/ilog-cplex-optimization-studio?S_PKG=CoG&cm_mmc=Search_Google-_-Data+Science_Data+Science-_-WW_IDA-_-+IBM++CPLEX_Broad_CoG&cm_mmca1=000000RE&cm_mmca2=10000668&cm_mmca7=9041989&cm_mmca8=kwd-412296208719&cm_mmca9=_k_Cj0KCQiAr93gBRDSARIsADvHiOpDUEHgUuzu8fJvf3vmO5rI0axgtaleqdmwk6JRPIDeNcIjgIHMhZIaAiwWEALw_wcB_k_&cm_mmca10=267798126431&cm_mmca11=b&mkwid=_k_Cj0KCQiAr93gBRDSARIsADvHiOpDUEHgUuzu8fJvf3vmO5rI0axgtaleqdmwk6JRPIDeNcIjgIHMhZIaAiwWEALw_wcB_k_%7C470%7C135655&cvosrc=ppc.google.%2Bibm%20%2Bcplex&cvo_campaign=000000RE&cvo_crid=267798126431&Matchtype=b&gclid=Cj0KCQiAr93gBRDSARIsADvHiOpDUEHgUuzu8fJvf3vmO5rI0axgtaleqdmwk6JRPIDeNcIjgIHMhZIaAiwWEALw_wcB) which is free for students and academics. 

Once you obtain the license, please let us know again and we would be more than happy to share with you the new PHONEMeS implementation.

Cheers,
Enio

**Comment by enio23** [comment]
> Hi
> I am planning to run Phonemes for some phosphoproteomic datasets. However I do not have IBM clusters available. Is it possible to run it on a multi core AWS system(16 cores, 60GB) ? If yes, can you point out where I would want to make changes. Thanks in advance.

Hello,

Thank you for your interest on using PHONEMeS. If you would like to run the tool in a cluster, then the modifications might have to be done in the shell script which is submitting and executing the jobs. On that case I would need to know the specifications of the cluster you will be using.

However, an alternative approach would be on using a new ILP implementation which makes the running much simpler in a stand alone PC and much faster. For that however, I would suggest you to first obtain a CPLEX license from IBM (https://www.ibm.com/products/ilog-cplex-optimization-studio?S_PKG=CoG&cm_mmc=Search_Google-_-Data+Science_Data+Science-_-WW_IDA-_-+IBM++CPLEX_Broad_CoG&cm_mmca1=000000RE&cm_mmca2=10000668&cm_mmca7=9041989&cm_mmca8=kwd-412296208719&cm_mmca9=_k_Cj0KCQiAr93gBRDSARIsADvHiOpDUEHgUuzu8fJvf3vmO5rI0axgtaleqdmwk6JRPIDeNcIjgIHMhZIaAiwWEALw_wcB_k_&cm_mmca10=267798126431&cm_mmca11=b&mkwid=_k_Cj0KCQiAr93gBRDSARIsADvHiOpDUEHgUuzu8fJvf3vmO5rI0axgtaleqdmwk6JRPIDeNcIjgIHMhZIaAiwWEALw_wcB_k_%7C470%7C135655&cvosrc=ppc.google.%2Bibm%20%2Bcplex&cvo_campaign=000000RE&cvo_crid=267798126431&Matchtype=b&gclid=Cj0KCQiAr93gBRDSARIsADvHiOpDUEHgUuzu8fJvf3vmO5rI0axgtaleqdmwk6JRPIDeNcIjgIHMhZIaAiwWEALw_wcB) which is free for students and academics.

Once you obtain the license, please let us know again and we would be more than happy to share with you the new PHONEMeS implementation.

Cheers,
Enio
