### ISSUE TITLE
Output description and some feature request

### ISSUE THREAD

**Issue by joonan30** [saezlab/PHONEMeS#6]
Thanks for the great tool. I have been using PHONEMeS for my phosphoproteomics dataset and seems the results are interesting. I have followed the tutorial here https://github.com/saezlab/PHONEMeS/blob/master/vignettes/tutorial.md and I think I got most of steps but some output description is missing. 

In the network attribution file ("networkAtt"), there is a column "nodesType", which has M and P. Is M for kinase (enzyme?) and P for phospshotase? or other meaning?

For top kinases in the network, I think I can use "kinase_activity score" or the number of out degree. Is there any further statistics to evaluate top kinase with the most significant regulation in the network?

Thanks

**Comment by smuellerd** [comment]
Hi @joonan30! Sorry for the late response.

in theory the "nodesType" column in the attribution file should contain S for source/inputted kinases and T for target/inputted phosphorylation site. I am not really sure why you get an M and a P and I would need some time to take a closer look. Maybe you can check if M or P correspond to your inputed deregulated_kinases or deregulated_pps. 

So far, we also use the out degree or the kinase activity score to check for kinases relevant in the regulation and there is no other statistic yet.

Best
Sophia
